name: CI/CD -> Docker Swarm

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and push backend image
      id: build-backend
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        IMAGE_BACKEND=${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
        docker build -t "$IMAGE_BACKEND" ./backend
        echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        docker push "$IMAGE_BACKEND"
        echo "IMAGE_BACKEND=$IMAGE_BACKEND" >> $GITHUB_OUTPUT

    - name: Build and push frontend image
      id: build-frontend
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        IMAGE_FRONTEND=${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
        docker build -t "$IMAGE_FRONTEND" ./frontend
        echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        docker push "$IMAGE_FRONTEND"
        echo "IMAGE_FRONTEND=$IMAGE_FRONTEND" >> $GITHUB_OUTPUT

    - name: Deploy to Swarm manager via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SWARM_MANAGER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          IMAGE_BACKEND=${{ steps.build-backend.outputs.IMAGE_BACKEND }}
          IMAGE_FRONTEND=${{ steps.build-frontend.outputs.IMAGE_FRONTEND }}
          docker pull "$IMAGE_BACKEND"
          docker pull "$IMAGE_FRONTEND"
          /home/ubuntu/deploy/deploy.sh "$IMAGE_BACKEND" "$IMAGE_FRONTEND"
