version: "3.8"
services:
  backend:
    image: BACKEND_IMAGE
    ports: []
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
  frontend:
    image: FRONTEND_IMAGE
    ports:
      - "80:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
networks:
  default:
    driver: overlay
